name: Dump GitHub Context

on: [push, pull_request]

jobs:
  context_dump:
    runs-on: ubuntu-latest
    steps:
      - name: Print Runner Info
        run: echo "Running on $(uname -a)"

      - name: Print GitHub Context
        run: echo '${{ toJson(github) }}'

      - name: Print Job Context
        run: echo '${{ toJson(job) }}'

      - name: Print Steps Context
        run: echo '${{ toJson(steps) }}'

      - name: Print Runner Context
        run: echo '${{ toJson(runner) }}'

      - name: Print Environment Variables
        run: printenv | sort

      - name: Completion Message
        run: echo "GitHub context dump completed!"
