name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "my first github action"  # Added 'run' 

            - name: list files
              run: cat README.md  # Fixed indentation
